name: rtd_ruspy

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.8
  - pip
  - sphinx

  - ipython
  - nbsphinx
  - numpydoc
  - sphinx-autobuild
  - sphinx-autoapi
  - numba

  - pip:
    - sphinx_rtd_theme
