name: rtd_ruspy

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9
  - pip
  - sphinx

  - ipython
  - nbsphinx
  - numpydoc
  - sphinx-autobuild
  - sphinx-autoapi

  - pip:
    - sphinx_rtd_theme
